@baseURL = http://localhost:3333
@authToken = {{ authenticate.response.body.token }}

# @name create_user
POST {{baseURL}}/users
Content-Type: application/json

{
  "name": "Thiago",
  "email": "thiago@mail.com",
  "password": "123456",
  "role": "manager"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "thiago@mail.com",
  "password": "123456"
}
